[tools]
bun = "latest"
eza = "latest"
"github:rossmacarthur/sheldon" = "latest"
go = "latest"
lazydocker = "latest"
"npm:@openai/codex" = "latest"
"npm:ccstatusline" = "latest"
"npm:obsidian-headless" = { version = "latest", npm_args = "--ignore-scripts=false" }
python = "latest"
ripgrep = "latest"
uv = "latest"
yarn = "latest"
zoxide = "latest"
lazygit = "latest"
neovim = "latest"
yazi = "latest"
node = "lts"
fzf = "latest"
usage = "latest"
gh = "latest"
"npm:playwright" = "latest"
"pipx:claude-real-video" = "latest"
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }
"github:RivoLink/leaf" = "latest"

[bootstrap.macos.finder]
show_pathbar = true
show_status_bar = true
preferred_view_style = "list"

[bootstrap.macos.keyboard]
fn_state = true

[bootstrap.macos.trackpad]
tap_to_click = true
three_finger_drag = false

[bootstrap.macos.defaults]
"com.apple.dock" = { tilesize = 16.0 }
"com.apple.finder" = { AppleShowAllFiles = "TRUE" }
NSGlobalDomain = { KeyRepeat = 2.0, InitialKeyRepeat = 15.0 }
