[tools]
bun = "latest"
"github:eza-community/eza" = "latest"
"github:jesseduffield/lazydocker" = "latest"
"github:jesseduffield/lazygit" = "latest"
"github:rossmacarthur/sheldon" = "latest"
"github:sxyazi/yazi" = "latest"
"github:twpayne/chezmoi" = "latest"
go = "latest"
node = "latest"
"npm:@openai/codex" = "latest"
"npm:ccstatusline" = "latest"
"npm:obsidian-headless" = "latest"
python = "latest"
usage = "latest"
uv = "latest"
yarn = "latest"
